version: "3.7"
services:
  php:
    image: pigmentpattern/php-fpm:8.3
    networks:
      - appnet
    volumes:
      - ".://var/www/:cached"
  nginx:
    image: pigmentpattern/nginx
    ports:
      - 8080:80
    networks:
      - appnet
    volumes:
      - ".://var/www/" 
  mysql:
    image: mysql:8
    ports:
     - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - appnet
  node:
    image: node:20
    volumes:
      - ".://var/www/"
    networks:
      - appnet
    ports:
     - 3000:3000
    expose:
     - 3000
networks:
  appnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"